### ISSUE TITLE
Fetch Generic model data?

### ISSUE THREAD

**Issue by EvgeniyReznichenko** [deblockt/hal-rest-client#8]
Hi Thomas,

One of my API endpoints returns me a set of similar structures which i'd like to map on my custom client side HAL resource model.

The output structure is looks like below:
```
data:
     set1:
           count: 3
           list: [type1, type1, type1]
     set2:
           count: 2
           list: [type2, type2]
     set3:
           count: 4
           list: [type3, type3, type3, type3]
```
So, I've tried to to map such a structure on the following kind of model:

```
class InfoSet<T extends HalResource> extends HalResource {
    @HalProperty()
    count: number;

    @HalProperty(T) <---- ERROR: 'T' only refers to a type, but is being used as a value here
    list: T[];
}

export class Data extends HalResource {
    @HalProperty(InfoSet)
    set1: InfoSet<Type1>;

    @HalProperty(InfoSet)
    set2: InfoSet<Type2>;

    @HalProperty(InfoSet)
    set3: InfoSet<Type3>;
}
```

But it shows an error as displayed above at 5th row

So I've tried to workaround that as like that:
```
class InfoSet<T extends HalResource> extends HalResource {
    test: T;

    @HalProperty()
    count: number;

    @HalProperty(typeof this.test) <--- No more error
    list: T[];
}
```

After that there were no any compile time issues anymore, but on application open , i've got the next error in browser console:
![image](https://user-images.githubusercontent.com/1070405/27080598-57161b9e-5045-11e7-91d1-6f502431ec21.png)

**Where DashboardInfo is the same InfoSet but in my real app.**

But T already extends  HalResource type..

Is it possible to map response data on typescript generic HAL models?
If yes, what am i doing wrong?

Regards,
Evgeniy
